name: build-documentation
on:
  push:
    branches:
      - "development"
  workflow_dispatch:

jobs:
  build-docc:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create folder for generated documentation
        run: mkdir -p docs

      - name: Build Documentation
        run: |
          xcodebuild docbuild \
            -scheme "Aurora Editor" \
            -destination generic/platform=macOS \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            DOCC_HOSTING_BASE_PATH="${{ github.event.repository.name }}" \
            OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path ${{ github.event.repository.name }} --output-path docs"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          DOCURL=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')
          echo "docs.auroraeditor.com" > CNAME
          echo "{\"meta\":{\"title\":\"$DOCURL Documentation\"}}" > theme-settings.json
          echo "<script>window.location.href = (document.location.host == 'auroraeditor.github.io' ? '/AuroraEditor' : '') + '/documentation/$DOCURL/'.toLowerCase();</script>" > index.html
          echo "<script>window.location.href = (document.location.host == 'auroraeditor.github.io' ? '/AuroraEditor' : '') + '/documentation/$DOCURL/'.toLowerCase();</script>" > 404.html
          git init -b documentation
          git add -A .
          git commit -m "Deploy documentation"
          git push -f "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" documentation:documentation
